id = "uxntal"
name = "Uxntal"
version = "0.1.0"
schema_version = 1
authors = ["Tyler Gardner <code@tylergardner.org>"]
description = "Uxntal Language Support"
repository = "https://github.com/TicTocCroc/zed-uxntal"

[grammars.uxntal]
repository = "https://github.com/TicTocCroc/tree-sitter-uxntal.git"
rev = "20b1f29f0b3f09aa73022e5e98fbe54bc3e31426"
