name = "Uxntal"
grammar = "uxntal"
path_suffixes = ["tal"]
tab_size = 2
hard_tabs = true
brackets = [
  { start = "( ", end = " )", close = true, newline = false, not_in = ["string", "comment"] }
]
documentation_comment = { start = "( ", prefix = "", end = " )", tab_size = 2 }
